services:
  django-multi:
    build:
      context: ./multi
    ports:
      - "8000:8000"
    volumes:
      - ./multi:/app
    environment:
      - DJANGO_SETTINGS_MODULE=multi.settings
      - PYTHONPATH=/app/multi

  django-simple:
    build:
      context: ./simple
    ports:
      - "8001:8000"
    volumes:
      - ./simple:/app
    environment:
      - DJANGO_SETTINGS_MODULE=simple.settings
      - PYTHONPATH=/app/simple
